<input type="text"
    class="py-2 px-3 block w-96 border-gray-300 text-sm focus:border-blue-500 focus:ring-blue-500 placeholder:text-gray-400"
    placeholder="small input" />
<input type="text"
    class="py-3 px-4 block w-96 border-gray-300 text-sm focus:border-blue-500 focus:ring-blue-500 placeholder:text-gray-400"
    placeholder="default input" />
<input type="text"
    class="py-3 px-4 sm:p-5 block w-96 border-gray-300 text-sm focus:border-blue-500 focus:ring-blue-500 placeholder:text-gray-400"
    placeholder="large input" />
